server:
  port: 8080
spring:
  application:
    name: springboot-rabbitmq
  #rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /